const STORAGE_KEY="taste-note-records-v1";
const icons={
espresso:'<svg viewBox="0 0 80 80"><path d="M18 30h39v20c0 9-7 15-19 15S18 59 18 50V30Z"/><path d="M57 35h5c7 0 10 4 10 9s-4 9-12 9M14 66h51M24 30c9 4 19 4 27 0M31 19c-4-5 4-7 0-12M43 19c-4-5 4-7 0-12"/></svg>',
americano:'<svg viewBox="0 0 80 80"><path d="M20 19h38l-4 48H24l-4-48Z"/><path d="M18 19h42M25 26c8 3 20 3 28 0M31 12c-3-4 3-6 0-9M43 12c-3-4 3-6 0-9"/></svg>',
latte:'<svg viewBox="0 0 80 80"><path d="M22 20h35l-3 47H25l-3-47Z"/><path d="M22 31h34M27 29c5-10 20-10 25 0M34 22c2 4 8 4 10 0"/></svg>',
filter:'<svg viewBox="0 0 80 80"><path d="M20 20h40L52 45H28L20 20Z"/><path d="M26 46h28M31 46v7h20v-7M24 58h34v10H24V58ZM31 13c-3-4 3-6 0-10M43 13c-3-4 3-6 0-10"/></svg>',
cold:'<svg viewBox="0 0 80 80"><path d="M24 13h32l-3 55H27l-3-55Z"/><path d="M24 40c9 4 20 4 31 0M31 26l8 8-7 7M46 21l7 7-8 8M47 5l-6 17"/></svg>',
otherCoffee:'<svg viewBox="0 0 80 80"><path d="M22 24h38v25c0 10-8 17-19 17S22 59 22 49V24Z"/><path d="M60 31h3c7 0 10 4 10 9s-4 9-11 9M18 67h49M30 14c4 4 18 4 22 0"/></svg>',
cake:'<svg viewBox="0 0 80 80"><path d="m13 59 50 7V32L29 20 13 32v27Z"/><path d="m13 32 50 8M19 46l44 7M29 20v12M34 17c0-5 7-5 7 0s-7 5-7 0Z"/></svg>',
croissant:'<svg viewBox="0 0 80 80"><path d="M12 50c5-22 17-31 28-31s23 9 28 31c-8 10-19 15-28 15S20 60 12 50Z"/><path d="M24 59c-2-18 4-32 16-40M56 59c2-18-4-32-16-40M12 50c9 1 14-2 18-8M68 50c-9 1-14-2-18-8"/></svg>',
cookie:'<svg viewBox="0 0 80 80"><path d="M64 37c-8 0-13-7-11-14-9-4-19-2-27 4-13 10-14 28-2 38s30 8 39-5c5-7 6-16 1-23Z"/><path d="M29 39h1M44 33h1M50 51h1M32 56h1"/></svg>',
macaron:'<svg viewBox="0 0 80 80"><path d="M15 35c2-12 12-20 25-20s23 8 25 20H15ZM15 47h50M19 35h42l4 12H15l4-12ZM19 47c2 11 10 18 21 18s19-7 21-18"/></svg>',
pudding:'<svg viewBox="0 0 80 80"><path d="M23 26h34l7 38H16l7-38Z"/><path d="M21 26c0-8 8-13 19-13s19 5 19 13c0 5-9 8-19 8s-19-3-19-8ZM27 15c5 5 21 5 26 0"/></svg>',
otherDessert:'<svg viewBox="0 0 80 80"><path d="M15 57c2-13 12-21 25-21s23 8 25 21H15Z"/><path d="M10 58h60M40 35V21M33 21h14M24 66h32M29 28c3 3 19 3 22 0"/></svg>'};
const items={coffee:[["espresso","에스프레소","ESPRESSO"],["americano","아메리카노","AMERICANO"],["latte","라테","CAFFÈ LATTE"],["filter","필터 커피","FILTER COFFEE"],["cold","콜드브루","COLD BREW"],["otherCoffee","다른 커피","OTHER"]],dessert:[["cake","케이크","CAKE"],["croissant","크루아상","CROISSANT"],["cookie","쿠키","COOKIE"],["macaron","마카롱","MACARON"],["pudding","푸딩","PUDDING"],["otherDessert","다른 디저트","OTHER"]]};
const ratingLabels=[["aroma","향"],["sweet","단맛"],["body","바디감"],["balance","균형"]];
const flavors=["고소한","초콜릿","캐러멜","과일","꽃향","시트러스","부드러운","바삭한","쌉쌀한","담백한"];
const beanIcon='<svg viewBox="0 0 20 26"><path d="M15 2C6 3 2 9 3 16c1 6 6 9 11 7 6-2 7-9 4-15-1-3-2-5-3-6Z"/><path d="M15 3c-1 8-8 10-11 14"/></svg>';
let activeCategory="coffee",selectedType="latte",overallScore=4,activeFilter="all",records=loadRecords();
const form=document.querySelector("#tastingForm"),itemGrid=document.querySelector("#itemGrid"),ratingList=document.querySelector("#ratingList"),flavorTags=document.querySelector("#flavorTags"),recordGrid=document.querySelector("#recordGrid"),nameInput=document.querySelector("#itemName"),dateInput=document.querySelector("#tastedAt"),memo=document.querySelector("#memo");
function todayString(){const n=new Date(),local=new Date(n.getTime()-n.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)}
function loadRecords(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(v)?v:[]}catch{return[]}}
function saveRecords(){localStorage.setItem(STORAGE_KEY,JSON.stringify(records))}
function renderItems(){itemGrid.innerHTML="";items[activeCategory].forEach(([id,ko,en])=>{const b=document.createElement("button");b.type="button";b.className=`item-option${selectedType===id?" active":""}`;b.setAttribute("aria-pressed",String(selectedType===id));b.innerHTML=`${icons[id]}<span>${ko}</span><small>${en}</small>`;b.addEventListener("click",()=>{selectedType=id;if(!nameInput.value.trim()||Object.values(items).flat().some(i=>i[1]===nameInput.value))nameInput.value=ko;renderItems()});itemGrid.appendChild(b)})}
function buildRatings(){ratingList.innerHTML=ratingLabels.map(([id,label])=>`<div class="rating-item"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="range" min="1" max="5" value="3"><output for="${id}">3</output></div>`).join("");ratingList.querySelectorAll("input").forEach(i=>i.addEventListener("input",()=>{i.nextElementSibling.value=i.value}))}
function buildFlavors(){flavorTags.innerHTML=flavors.map(f=>`<button class="flavor-tag" type="button" aria-pressed="false">${f}</button>`).join("");flavorTags.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{b.classList.toggle("active");b.setAttribute("aria-pressed",String(b.classList.contains("active")))}))}
function renderOverall(){const c=document.querySelector("#overallRating");c.innerHTML=Array.from({length:5},(_,i)=>`<button class="score-button${i<overallScore?" active":""}" type="button" aria-label="만족도 ${i+1}점" aria-pressed="${i+1===overallScore}">${beanIcon}</button>`).join("");c.querySelectorAll("button").forEach((b,i)=>b.addEventListener("click",()=>{overallScore=i+1;renderOverall()}))}
function itemDetails(type){return Object.entries(items).flatMap(([category,list])=>list.map(([id,ko,en])=>({id,ko,en,category}))).find(i=>i.id===type)}
function formatDate(v){const[y,m,d]=v.split("-");return`${y}.${m}.${d}`}
function renderScore(score){return Array.from({length:5},(_,i)=>beanIcon.replace("<svg",`<svg class="${i<score?"":"off"}"`)).join("")}
function escapeHtml(v){const s=document.createElement("span");s.textContent=String(v||"");return s.innerHTML}
function renderRecords(){const filtered=activeFilter==="all"?records:records.filter(r=>r.category===activeFilter);recordGrid.innerHTML="";if(!filtered.length){recordGrid.appendChild(document.querySelector("#emptyTemplate").content.cloneNode(true));return}filtered.sort((a,b)=>b.createdAt-a.createdAt).forEach(r=>{const details=itemDetails(r.type)||itemDetails(r.category==="coffee"?"otherCoffee":"otherDessert"),card=document.createElement("article");card.className="record-card";card.innerHTML=`<div class="record-card-top"><span class="record-kind">${r.category.toUpperCase()} · ${formatDate(r.date)}</span><span class="record-icon">${icons[r.type]||icons[details.id]}</span></div><h3>${escapeHtml(r.name)}</h3><p class="record-meta">${r.place?escapeHtml(r.place):"장소 미기록"} · ${details.ko}</p><div class="record-flavors">${r.flavors.map(f=>`<span>${f}</span>`).join("")}</div>${r.memo?`<p class="record-memo">“${escapeHtml(r.memo)}”</p>`:""}<div class="record-bottom"><span class="record-score" aria-label="만족도 ${r.score}점">${renderScore(r.score)}</span><button class="delete-record" type="button" data-id="${r.id}">삭제</button></div>`;recordGrid.appendChild(card)});recordGrid.querySelectorAll(".delete-record").forEach(b=>b.addEventListener("click",()=>{records=records.filter(r=>r.id!==b.dataset.id);saveRecords();renderRecords()}))}
document.querySelectorAll(".category-tab").forEach(tab=>tab.addEventListener("click",()=>{activeCategory=tab.dataset.category;selectedType=items[activeCategory][0][0];document.querySelectorAll(".category-tab").forEach(b=>{const active=b===tab;b.classList.toggle("active",active);b.setAttribute("aria-selected",String(active))});renderItems()}));
document.querySelectorAll(".filter-button").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;document.querySelectorAll(".filter-button").forEach(i=>i.classList.toggle("active",i===b));renderRecords()}));
memo.addEventListener("input",()=>{document.querySelector("#memoCount").textContent=memo.value.length});document.querySelector("#headerWrite").addEventListener("click",()=>document.querySelector("#write").scrollIntoView({behavior:"smooth"}));document.querySelector("#clearRecords").addEventListener("click",()=>{if(!records.length||!window.confirm("저장된 모든 맛 기록을 비울까요?"))return;records=[];saveRecords();renderRecords()});
form.addEventListener("submit",event=>{event.preventDefault();const details=itemDetails(selectedType),selectedFlavors=[...flavorTags.querySelectorAll(".active")].map(b=>b.textContent),ratings=Object.fromEntries(ratingLabels.map(([id])=>[id,Number(document.querySelector(`#${id}`).value)])),record={id:`${Date.now()}-${Math.random().toString(16).slice(2)}`,createdAt:Date.now(),category:activeCategory,type:selectedType,name:nameInput.value.trim()||details.ko,place:document.querySelector("#place").value.trim(),date:dateInput.value,memo:memo.value.trim(),flavors:selectedFlavors,ratings,score:overallScore};records.unshift(record);saveRecords();renderRecords();form.reset();dateInput.value=todayString();overallScore=4;buildRatings();buildFlavors();renderOverall();document.querySelector("#memoCount").textContent="0";const message=document.querySelector("#formMessage");message.textContent="오늘의 맛이 기록되었습니다.";setTimeout(()=>{message.textContent=""},2600);document.querySelector("#archive").scrollIntoView({behavior:"smooth"})});
dateInput.value=todayString();renderItems();buildRatings();buildFlavors();renderOverall();renderRecords();
